// This file is auto-generated by scripts/generate-daily-task-icons.mjs.
// Do not edit this file manually.
export const dailyTaskIcons = {
  "buy_building_1": "assets/daily-tasks/buy_building_1.svg",
  "buy_building_10": "assets/daily-tasks/buy_building_10.svg",
  "buy_tech_1": "assets/daily-tasks/buy_tech_1.svg",
  "clicks_1000": "assets/daily-tasks/clicks_1000.svg",
  "combo_streak_60s": "assets/daily-tasks/combo_streak_60s.svg",
  "earn_population_today": "assets/daily-tasks/earn_population_today.svg",
  "fast_casts_5": "assets/daily-tasks/fast_casts_5.svg",
  "increase_prestige_mult": "assets/daily-tasks/increase_prestige_mult.svg",
  "loyly_100": "assets/daily-tasks/loyly_100.svg",
  "loyly_250": "assets/daily-tasks/loyly_250.svg",
  "loyly_500": "assets/daily-tasks/loyly_500.svg",
  "prestige_once": "assets/daily-tasks/prestige_once.svg",
  "reach_temp_1e10": "assets/daily-tasks/reach_temp_1e10.svg",
  "reach_temp_1e16": "assets/daily-tasks/reach_temp_1e16.svg",
  "reach_temp_1e6": "assets/daily-tasks/reach_temp_1e6.svg",
  "session_10min": "assets/daily-tasks/session_10min.svg",
  "unlock_next_tier": "assets/daily-tasks/unlock_next_tier.svg",
  "upgrade_same_building_3": "assets/daily-tasks/upgrade_same_building_3.svg",
} satisfies Record<string, string>;

export type DailyTaskIconId = keyof typeof dailyTaskIcons;
